version: 2.1

# https://circleci.com/docs/2.0/reusing-config/#invoking-reusable-commands
commands:
  build-project:
    description: "Build API the project - from /api folder"
    steps:
      - run: |
          cd ./api

orbs:
  node: circleci/node@4.2.1 # https://circleci.com/developer/orbs/orb/circleci/node
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  deploy-api:
    resource_class: micro
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - node/install-packages:
          pkg-manager: yarn
      - build-project
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'

workflows:
  version: 2
  deploy_services:
    jobs:
      - deploy-api
